Repository nuxt/image, pull requests merged in 2023-06, with the labels that each got.

#840 feat: add `none` provider and only enable `ipx` when node present
  package.json
  playground/nuxt.config.ts
  playground/providers.ts
  pnpm-lock.yaml
  src/ipx.ts
  src/module.ts
  src/provider.ts
  src/runtime/providers/none.ts
  test/e2e/__snapshots__/no-ssr.test.ts.snap
  test/e2e/__snapshots__/ssr.test.ts.snap
  test/providers.ts
  test/unit/providers.test.ts
Labels: enhancement

#787 feat: add `directus` provider
  docs/content/5.providers/directus.md
  playground/nuxt.config.ts
  playground/providers.ts
  src/provider.ts
  src/runtime/providers/directus.ts
  test/e2e/__snapshots__/no-ssr.test.ts.snap
  test/e2e/__snapshots__/ssr.test.ts.snap
  test/providers.ts
Labels: enhancement, provider

#842 fix: emit synthetic load/error events on initial hydration
  src/runtime/components/nuxt-img.ts
  src/runtime/components/nuxt-picture.ts
  test/e2e/no-ssr.test.ts
  test/e2e/ssr.test.ts
Labels: bug

#774 feat: add `wagtail` provider
  playground/nuxt.config.ts
  playground/pages/provider/[provider].vue
  playground/providers.ts
  src/provider.ts
  src/runtime/providers/wagtail.ts
  src/types/module.ts
  test/e2e/__snapshots__/no-ssr.test.ts.snap
  test/e2e/__snapshots__/ssr.test.ts.snap
  test/providers.ts
  test/unit/providers.test.ts
Labels: enhancement, provider

#676 fix: apply `sizes`/`srcset` when using placeholder
  .gitignore
  playground/pages/responsive.vue
  src/runtime/components/nuxt-img.ts
  test/unit/image.test.ts
Labels: bug

#860 fix: run setup and add `none` to providers list
  src/module.ts
Labels: bug

#760 fix: remove `key` for picture/image to stop flicker when loading
  src/runtime/components/nuxt-img.ts
  src/runtime/components/nuxt-picture.ts
Labels: bug

#823 feat: add `prepr` cms image provider integration
  docs/content/5.providers/prepr.md
  playground/nuxt.config.ts
  playground/providers.ts
  src/module.ts
  src/provider.ts
  src/runtime/providers/prepr/formatter.ts
  src/runtime/providers/prepr/getImage.ts
  src/runtime/providers/prepr/index.ts
  src/runtime/providers/prepr/keyMap.ts
  src/runtime/providers/prepr/valueMap.ts
  test/e2e/__snapshots__/no-ssr.test.ts.snap
  test/e2e/__snapshots__/ssr.test.ts.snap
  test/providers.ts
  test/unit/providers.test.ts
Labels: enhancement, provider

#872 fix: address miscellaneous bugs with new 'densities' prop
  src/runtime/components/nuxt-img.ts
  src/runtime/image.ts
  src/runtime/utils/index.ts
  src/types/image.ts
  test/unit/image.test.ts
  test/unit/picture.test.ts
Labels: bug, enhancement

#740 feat: add `uploadcare` provider
  docs/content/5.providers/uploadcare.md
  playground/nuxt.config.ts
  playground/providers.ts
  src/provider.ts
  src/runtime/providers/uploadcare.ts
  src/types/module.ts
  test/e2e/__snapshots__/no-ssr.test.ts.snap
  test/e2e/__snapshots__/ssr.test.ts.snap
  test/providers.ts
  test/unit/providers.test.ts
Labels: enhancement, provider
